# GoReleaser configuration for Terraform Provider
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Chainlaunch Terraform Provider {{ .Tag }}

    Welcome to this new release of the Chainlaunch Terraform Provider!

  footer: |
    ## Installation

    To use this provider, add it to your Terraform configuration:

    ```hcl
    terraform {
      required_providers {
        chainlaunch = {
          source  = "kfsoftware/chainlaunch"
          version = "~> {{ .Version }}"
        }
      }
    }

    provider "chainlaunch" {
      url      = "https://your-chainlaunch-instance.com"
      username = "admin"
      password = "your-password"
    }
    ```

    ## Documentation

    Full documentation is available at the [Terraform Registry](https://registry.terraform.io/providers/kfsoftware/chainlaunch/{{ .Version }}).

    ## Feedback

    Please report any issues or feature requests on [GitHub](https://github.com/kfsoftware/terraform-provider-chainlaunch/issues).

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: 'Dependency Updates'
      regexp: "^.*build\\(deps\\)*:+.*$"
      order: 3
    - title: 'Other Changes'
      order: 999

# Terraform Provider specific settings
# This ensures compatibility with Terraform Registry requirements
snapshot:
  name_template: "{{ .Tag }}-next"
