# Pre-commit hooks for Terraform provider
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Terraform formatting and validation
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
        name: Terraform fmt
        description: Formats Terraform files
        files: \.tf$

      - id: terraform_validate
        name: Terraform validate
        description: Validates Terraform configurations
        files: \.tf$
        exclude: ^test/

      - id: terraform_tflint
        name: Terraform lint
        description: Lints Terraform files with tflint
        files: \.tf$
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

  # Go formatting and linting
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go
        entry: golangci-lint run --fix
        types: [go]
        language: system
        pass_filenames: false

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        name: go fmt
        description: Formats Go code
        types: [go]

      - id: go-mod-tidy
        name: go mod tidy
        description: Tidies Go module dependencies
        types: [go]
        pass_filenames: false

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        description: Removes trailing whitespace

      - id: end-of-file-fixer
        name: Fix end of files
        description: Ensures files end with a newline

      - id: check-yaml
        name: Check YAML
        description: Validates YAML files

      - id: check-added-large-files
        name: Check for large files
        description: Prevents large files from being committed
        args: ['--maxkb=1000']

      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Checks for files with merge conflict markers

      - id: check-case-conflict
        name: Check case conflicts
        description: Checks for files with case conflicts

      - id: mixed-line-ending
        name: Fix mixed line endings
        description: Ensures consistent line endings

  # Markdown linting
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        name: Markdown lint
        description: Lints markdown files
        files: \.md$
        args: ['--git-recurse', '--config', '.markdownlint.json']
        exclude: ^(docs/|examples/.*/README\.md)

  # JSON formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: pretty-format-json
        name: Format JSON
        description: Formats JSON files
        args: ['--autofix', '--indent=2']
        files: \.json$
        exclude: ^(\.vscode/|package-lock\.json)
